version: "3.1"

services:
  postgres:
    image: postgres:latest
  redis:
    image: redis:latest
  api:
    build:
      dockerfile: Dockerfile.prod
      context: ./udemy_complex/server
    volumes:
      - /app/node_modules
      - ./udemy_complex/server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - PGHOST=postgres
      - POSTGRES_DB=postgresProd
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./udemy_complex/client
    volumes:
      - /app/node_modules
      - ./udemy_complex/client:/app
  worker:
    build:
      dockerfile: Dockerfile.prod
      context: ./udemy_complex/worker
    volumes:
      - /app/node_modules
      - ./udemy_complex/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build:
      dockerfile: Dockerfile.prod
      context: ./udemy_complex/nginx
    restart: always
    ports:
      - "8098:80"
